branch-defaults:
  master:
    environment: scribble-env
global:
  application_name: scribble
  default_platform: 64bit Amazon Linux 2017.09 v2.6.2 running Ruby 2.4 (Passenger Standalone)
  default_region: us-east-2
  sc: git
